name: Build and Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build binary
        run: cd ./app && go build -v -o ../codecrafters-redis-go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: codecrafters-redis-go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

